name: st
channels:
  - http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - _r-mutex=1.0.1
  - binutils_impl_linux-64=2.40
  - bwidget=1.10.1
  - bzip2=1.0.8
  - c-ares=1.34.4
  - ca-certificates=2025.2.25
  - cairo=1.18.0
  - curl=8.12.1
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - freetype=2.13.3
  - fribidi=1.0.10
  - gcc_impl_linux-64=14.2.0
  - gettext=0.23.1
  - gettext-tools=0.23.1
  - gfortran_impl_linux-64=14.2.0
  - graphite2=1.3.13
  - gxx_impl_linux-64=14.2.0
  - harfbuzz=8.3.0
  - icu=73.2
  - kernel-headers_linux-64=3.10.0
  - keyutils=1.6.1
  - krb5=1.21.3
  - ld_impl_linux-64=2.40
  - lerc=4.0.0
  - libasprintf=0.23.1
  - libasprintf-devel=0.23.1
  - libblas=3.9.0
  - libcurl=8.12.1
  - libdeflate=1.23
  - libedit=3.1.20191231
  - libev=4.33
  - libexpat=2.6.4
  - libffi=3.4.6
  - libgcc=14.2.0
  - libgcc-devel_linux-64=14.2.0
  - libgcc-ng=14.2.0
  - libgettextpo=0.23.1
  - libgettextpo-devel=0.23.1
  - libgfortran=14.2.0
  - libgfortran-ng=14.2.0
  - libgfortran5=14.2.0
  - libglib=2.78.1
  - libgomp=14.2.0
  - libiconv=1.18
  - libjpeg-turbo=3.0.0
  - liblapack=3.9.0
  - liblzma=5.6.4
  - libnghttp2=1.64.0
  - libnsl=2.0.1
  - libopenblas=0.3.29
  - libpng=1.6.47
  - libsanitizer=14.2.0
  - libsqlite=3.45.2
  - libssh2=1.11.1
  - libstdcxx=14.2.0
  - libstdcxx-devel_linux-64=14.2.0
  - libstdcxx-ng=14.2.0
  - libtiff=4.7.0
  - libuuid=2.38.1
  - libwebp-base=1.5.0
  - libxcb=1.15
  - libxcrypt=4.4.36
  - libzlib=1.3.1
  - make=4.4.1
  - ncurses=6.4
  - openssl=3.4.1
  - pango=1.50.14
  - pcre2=10.40
  - pip=25.0
  - pixman=0.44.2
  - pthread-stubs=0.4
  - python=3.9.18
  - r-base=4.3.1
  - readline=8.2
  - sed=4.8
  - setuptools=75.8.0
  - sqlite=3.45.2
  - sysroot_linux-64=2.17
  - tk=8.6.13
  - tktable=2.10
  - wheel=0.45.1
  - xorg-kbproto=1.0.7
  - xorg-libice=1.1.2
  - xorg-libsm=1.2.6
  - xorg-libx11=1.8.9
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.4
  - xorg-libxrender=0.9.11
  - xorg-libxt=1.3.0
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.6.4
  - zlib=1.3.1
  - zstd=1.5.7
  - pip:
      - anndata==0.10.9
      - array-api-compat==1.11.2
      - certifi==2025.1.31
      - cffi==1.17.1
      - charset-normalizer==3.4.1
      - contourpy==1.3.0
      - cycler==0.12.1
      - dill==0.3.9
      - e==1.4.5
      - exceptiongroup==1.2.2
      - fonttools==4.56.0
      - get-annotations==0.1.2
      - h5py==3.13.0
      - idna==3.10
      - importlib-resources==6.5.2
      - jinja2==3.1.6
      - joblib==1.4.2
      - kiwisolver==1.4.7
      - legacy-api-wrap==1.4.1
      - llvmlite==0.43.0
      - markupsafe==3.0.2
      - matplotlib==3.9.4
      - natsort==8.4.0
      - networkx==3.2.1
      - numba==0.60.0
      - numpy==1.26.4
      - nvidia-cublas-cu11==11.10.3.66
      - nvidia-cuda-nvrtc-cu11==11.7.99
      - nvidia-cuda-runtime-cu11==11.7.99
      - nvidia-cudnn-cu11==8.5.0.96
      - packaging==24.2
      - pandas==2.2.3
      - patsy==1.0.1
      - pillow==11.1.0
      - pot==0.9.5
      - pycparser==2.22
      - pynndescent==0.5.13
      - pyparsing==3.2.1
      - python-dateutil==2.9.0.post0
      - pytz==2025.1
      - pyyaml==6.0.2
      - requests==2.32.3
      - rpy2==3.5.17
      - scanpy==1.10.3
      - scikit-learn==1.6.1
      - scipy==1.13.1
      - seaborn==0.13.2
      - session-info==1.0.0
      - six==1.17.0
      - statsmodels==0.14.4
      - stdlib-list==0.11.1
      - threadpoolctl==3.6.0
      - torch==1.13.1
      - torchaudio==0.13.1
      - torchvision==0.14.1
      - tqdm==4.67.1
      - typing-extensions==4.12.2
      - tzdata==2025.1
      - tzlocal==5.3.1
      - umap-learn==0.5.7
      - urllib3==2.3.0
      - zipp==3.21.0
